name: Node.js Test and Deploy Staging

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run-script test a
      env:
        CI: true
        REACT_APP_MAPS_TOKEN: ${{ secrets.MYDENTUREPLACE_STAGING_REACT_APP_MAPS_TOKEN }}
        
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run-script build
    - uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
    - uses: JesseTG/rm@v1.0.0
      with:
        path: build
      env:
        AWS_S3_BUCKET: ${{ secrets.MYDENTUREPLACE_STAGING_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.MYDENTUREPLACE_DEPLOY_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MYDENTUREPLACE_DEPLOY_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-2'
        SOURCE_DIR: 'build'
        REACT_APP_MAPS_TOKEN: ${{ secrets.MYDENTUREPLACE_STAGING_REACT_APP_MAPS_TOKEN }}
        CI: true
