name: Node.js Test Staging

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run-script test a
      env:
        CI: true
        REACT_APP_MAPS_TOKEN: pk.eyJ1Ijoia2V2aW5rYW0xMjMiLCJhIjoiY2s2NmFhaXFmMTQ4aTNlbzhocGxibTZqYiJ9.zzH6FWL717qrOeerOKAHnA
